---
- name: Pass bridged IPv4/IPv6 traffic to iptables' chains
  sysctl:
    name: '{{ item }}'
    value: 1
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

#- name: Pass and reload bridged IPv4/IPv6 traffic to iptables' chains
#  sysctl:
#    name: '{{ item }}'
#    value: 1
#    state: present
#    reload: yes
#    sysctl_set: yes
#  with_items:
#    - net.bridge.bridge-nf-call-iptables
#    - net.bridge.bridge-nf-call-ip6tables

- name: Ensure kubelet is started and enabled at boot.xxxxxxxxx
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - docker
    - kubelet

- name: kubeadm init | Initializing K8s cluster
  shell: >
    kubeadm reset &&
    sysctl -p &&
    kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16 --kubernetes-version=v{{ version_kube }}
  args:
    creates: /etc/kubeadm-join.sh
  register: kubeadm_join_out

- name: Save '/etc/kubeadm-join.sh' into K8s master
  lineinfile:
    path: /etc/kubeadm-join.sh
    line: '{{ kubeadm_join_out.stdout_lines[-1] }}'
    create: yes
  when: kubeadm_join_out.stdout.find("kubeadm join") != -1

- name: Poke Kubelet systemd service
  systemd:
    name: kubelet
    state: started
    enabled: yes
