- name: configure ubuntu | Install modules into Linux Kernel.
  command: modprobe {{ item }}
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

- name: configure ubuntu | Update '/etc/modules' file.
  lineinfile:
    path: /etc/modules
    line: '{{ item }}'
    create: yes
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

- name: configure ubuntu | Setup 'net.ipv4.ip_forward'
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
    sysctl_set: yes
