- name: Pull Docker images
  shell: 'docker pull {{ item.path }}/{{ item.img }}:{{ item.tag }}'
  with_items:
    - { path: 'k8s.gcr.io', img: 'kube-apiserver-arm', tag: 'v{{ _k8s_version }}'}
    - { path: 'k8s.gcr.io', img: 'kube-controller-manager-arm', tag: 'v{{ _k8s_version }}'}
    - { path: 'k8s.gcr.io', img: 'kube-scheduler-arm', tag: 'v{{ _k8s_version }}'}
    - { path: 'k8s.gcr.io', img: 'etcd-arm', tag: '3.1.12'}
