---
- name: Check if Docker is already present
  command: which docker
  failed_when: False
  changed_when: False
  register: docker_command_result

### docker_command_result.rc == 1 (docker isn't installed)

- name: Install Docker through APT Repository
  include_tasks: install-docker-repo.yml
  when: docker_command_result.rc == 1 and _docker_installation_method == 'deb_repo' and ( _target_distribution == 'raspbian' or _target_distribution == 'debian' )

- name: Install Docker through Convenience Script
  include_tasks: install-docker-convenience.yml
  when: docker_command_result.rc == 1 and _docker_installation_method == 'convenience'

#- name: Restart Docker systemd services
#  service:
#    name: docker
#    state: restarted

- name: Ensure Docker systemd service is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes
